### ISSUE TITLE
Typo in id

### ISSUE THREAD

**Issue by Huntelaer** [rmuit/PracticalAfas#11]
https://github.com/rmuit/PracticalAfas/blob/51f28f0c1b11b9437647642ed80f00a7acf1e996/src/Connection.php#L66

Must be const OP_NOT_ENDS_WITH = 14;

See [
![Aantekening 2020-09-08 161116](https://user-images.githubusercontent.com/60963384/92487732-f0ef9e00-f1ed-11ea-8d47-ed7f88cc7ba5.jpg)
](https://connect.afas.nl/rest-json/get-connector)

**Comment by rmuit** [comment]
Thank you! Fixed.
